### PR TITLE
Hey I added Postgres support

### PR DESCRIPTION
**Pull request by jaeschliman**
sorry the commits are a little messy. I was having some weirrd issue with the public directory, but anyway, it loads up postgres and connects now. :)

### CODE REVIEW

**Comment by mtravers** [comment]
Thanks!

I had already started to add this, so didn't merge your pull altogether, but I did grab some of your code. It's now working; I have a couple of demo pages up (http://blooming-winter-9673.herokuapp.com/db-demo) but need to pretty them up and link them to the home page.

Mike

**Comment by jaeschliman** [comment]
cool glad i could help

**Comment by mtravers** [comment]
Lisp and Postrgres and Heroku and Ajax, all working together:
http://lisp-example.herokuapp.com/db-demo

On Mon, Apr 16, 2012 at 6:12 AM, Jason Aeschliman <
reply@reply.github.com

**Comment by jaeschliman** [comment]
hmm it's coming up blank for me :|

**Comment by mtravers** [comment]
It's working now...there's some sort of initialization problem which I
don't have time to look at now.

On Mon, Apr 16, 2012 at 9:13 AM, Jason Aeschliman <
reply@reply.github.com

**Pull request closed without merging**
